# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
inhibit_all_warnings!
target '新闻阅读APP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 新闻阅读APP
  # 一个项目中第一次使用pod install，以后都使用pod update
  # 导入AFN
  pod 'AFNetworking'
  pod 'SVProgressHUD'
  pod 'SnapKit', '~> 4.0'
  pod 'SDWebImage'
  pod 'SwiftyJSON'
  pod 'MJRefresh'
end
